[project]
name = "hearttablet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aqt[qt6]>=25.9.2",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
]
